// All user-facing copy (Hebrew). Wording rules: docs/product-spec.md — never "safe", always "visual".
export const he = {
  appName: 'סורק פירות וירקות',
  cameraHint: 'צלמו פרי או ירק אחד, מקרוב ובאור טוב',
  scan: 'סרוק פרי',
  scanAnother: 'סרוק פרי נוסף',
  anotherAngle: 'צלם מזווית נוספת',
  anotherAngleHint: 'צלמו את אותו הפרי מצד אחר',
  tryAgain: 'נסה שוב',
  unsureTitle: 'לא בטוח',
  retakeTitle: 'צריך צילום נוסף',
  notProduceTitle: 'לא זוהה פרי או ירק',
  identifyOnly: 'זיהוי בלבד · הערכת בשילות וטריות לסוג זה עוד לא זמינה',
  storageTip: 'טיפ אחסון (כללי)',
  trustLine: 'מעובד במכשיר · בלי הרשמה · בלי פרסומות',
  cameraFooter: 'הערכה חזותית · מעובד במכשיר',
  analyzing: 'בודק…',
  permissionTitle: 'צריך גישה למצלמה',
  permissionBody: 'כדי להעריך פרי צריך לצלם אותו. התמונה מעובדת במכשיר ואינה נשמרת – אלא אם תבחרו לשתף אותה.',
  permissionButton: 'אישור גישה',
  noEngine: 'המודל אינו זמין במכשיר הזה.',
  error: 'משהו השתבש. נסו שוב.',
  qualityScore: 'ציון איכות חזותי',
  outOf10: 'מתוך 10',
  ripeness: 'בשילות',
  freshness: 'טריות',
  spoilage: 'סימני קלקול',
  skin: 'מראה הקליפה',
  touch: 'מרקם – לבדוק ביד',
  touchNote: 'עצה כללית לסוג הפרי, לא מדידה מהתמונה',
  details: 'פרטי הניתוח',
  myScans: 'הסריקות שלי',
  back: 'חזרה',
  deleteScan: 'מחיקת הסריקה',
  clearAll: 'מחיקת הכול',
  clearAllTitle: 'למחוק את כל הסריקות השמורות?',
  noScansYet: 'עוד אין סריקות.',
  noScansBody: 'כל פרי שתסרקו יופיע כאן – עם התמונה, הציון והתאריך.',
  firstScan: 'לסריקה הראשונה',
  scansCount: 'סריקות',
  inGoodShape: 'במצב טוב',
  notRecommended: 'לא מומלצים',
  savedOnDevice: 'נשמר רק במכשיר הזה.',
  identifyOnlyShort: 'זיהוי בלבד',
  newScan: 'לסריקה חדשה',
  signInCta: 'התחברו כדי לשמור את הסריקות בחשבון ולראות אותן גם באתר ובכל מכשיר.',
  signInGoogle: 'התחברות עם Google',
  signInFailed: 'ההתחברות לא הושלמה. אפשר לנסות שוב.',
  signedInAs: 'מחוברים',
  signOut: 'התנתקות',
  deleteAccount: 'מחיקת החשבון',
  deleteAccountTitle: 'למחוק את החשבון ואת כל הסריקות השמורות בו?',
  deleteAccountBody: 'אי אפשר לבטל. הסריקות במכשיר הזה יישארו.',
  deleteFailed: 'המחיקה לא הצליחה. נסו שוב.',
  savedInAccount: 'נשמר בחשבון שלכם – זמין גם באתר ובכל מכשיר.',
  recommendation: 'המלצה',
  confidence: 'ביטחון בזיהוי',
  notAvailable: 'לא זמין עדיין לסוג זה',
  whatWeSaw: 'מה זיהינו?',
  why: 'מה גרם למודל לחשוב כך?',
  retake: 'צילום נוסף',
  wasItRight: 'האם הזיהוי נכון?',
  yes: 'כן',
  no: 'לא',
  thanks: 'תודה! המשוב עוזר לשפר את המודל.',
  credits: 'קרדיט לנתונים',
  creditsIntro: 'המודל אומן על מאגרי תמונות ציבוריים באישור הרישיון שלהם:',
  modelVersion: 'גרסת מודל',
  donateAsk: 'רוצים לעזור ללמד את המודל פירות מישראל?',
  donateButton: 'שיתוף התמונה',
  donateConsent: 'התמונה תישמר ותשמש לאימון המודל על פירות וירקות בישראל. נשלחים רק התמונה (מוקטנת, בלי מיקום ובלי פרטי מכשיר) והזיהוי. אין שם, חשבון או מזהה – לכן אי אפשר לשייך אותה אליכם, וגם לא למחוק אותה בהמשך. לא לשתף תמונה שמופיעים בה אנשים או מסמכים.',
  donateConfirm: 'מסכים/ה, לשתף',
  donateCancel: 'ביטול',
  donateSending: 'שולח…',
  donateThanks: 'תודה! התמונה נשלחה.',
  donateFailed: 'השליחה לא הצליחה. אפשר לנסות שוב.',
  visualOnlyBanner: 'הערכה חזותית בלבד',
};
