// All user-facing copy (Hebrew). Wording rules: docs/product-spec.md — never "safe", always "visual".
export const he = {
  appName: 'Scan Fruit AI',
  cameraHint: 'צלמו פרי או ירק אחד, מקרוב ובאור טוב',
  scan: 'סריקה',
  scanAnother: 'סריקה נוספת',
  anotherAngle: 'צלם מזווית נוספת',
  anotherAngleHint: 'צלמו את אותו הפרי או הירק מצד אחר',
  betterAngleTitle: 'רוצים תשובה מדויקת יותר?',
  betterAngleBody: (hint: string) => `אנחנו לא בטוחים לגמרי במצב שלו. ${hint} – ונשלב את שתי התמונות לתשובה אחת.`,
  tryAgain: 'נסה שוב',
  unsureTitle: 'לא בטוח',
  retakeTitle: 'צריך צילום נוסף',
  notProduceTitle: 'לא זוהה פרי או ירק',
  identifyOnly: 'זיהוי בלבד · הערכת בשילות וטריות לסוג זה עוד לא זמינה',
  storageTip: 'טיפ אחסון (כללי)',
  trustLine: 'התמונה לא נשמרת · בלי הרשמה · בלי פרסומות',
  cameraFooter: 'הערכה חזותית · התמונה לא נשמרת',
  analyzing: 'בודק…',
  permissionTitle: 'צריך גישה למצלמה',
  permissionBody: 'כדי להעריך פרי צריך לצלם אותו. התמונה נשלחת לניתוח בשרת שלנו ולא נשמרת – אלא אם תבחרו לשתף אותה.',
  permissionButton: 'אישור גישה',
  noEngine: 'המודל אינו זמין במכשיר הזה.',
  error: 'משהו השתבש. נסו שוב.',
  qualityScore: 'ציון איכות חזותי',
  outOf10: 'מתוך 10',
  ripeness: 'בשילות',
  freshness: 'טריות',
  spoilage: 'סימני קלקול',
  skin: 'מראה הקליפה',
  touch: 'מרקם – לבדוק ביד',
  touchNote: 'עצה כללית לסוג, לא מדידה מהתמונה',
  details: 'פרטי הניתוח',
  myScans: 'הסריקות שלי',
  profile: 'הפרופיל שלי',
  guest: 'אורח',
  guestSub: 'הסריקות נשמרות רק במכשיר הזה',
  signedInGoogle: 'מחוברים עם Google',
  recentScans: 'הסריקות האחרונות',
  allScans: 'לכל הסריקות',
  favType: 'הכי הרבה סרקתם',
  back: 'חזרה',
  deleteScan: 'מחיקת הסריקה',
  clearAll: 'מחיקת הכול',
  clearAllTitle: 'למחוק את כל הסריקות השמורות?',
  noScansYet: 'עוד אין סריקות.',
  noScansBody: 'כל פרי שתסרקו יופיע כאן – עם התמונה, הציון והתאריך.',
  firstScan: 'לסריקה הראשונה',
  scansCount: 'סריקות',
  inGoodShape: 'במצב טוב',
  notRecommended: 'לא מומלצים',
  savedOnDevice: 'נשמר רק במכשיר הזה.',
  identifyOnlyShort: 'זיהוי בלבד',
  newScan: 'לסריקה חדשה',
  signInCta: 'התחברו כדי לשמור את הסריקות בחשבון ולראות אותן גם באתר ובכל מכשיר.',
  signInGoogle: 'התחברות עם Google',
  signInFailed: 'ההתחברות לא הושלמה. אפשר לנסות שוב.',
  signedInAs: 'מחוברים',
  signOut: 'התנתקות',
  deleteAccount: 'מחיקת החשבון',
  deleteAccountTitle: 'למחוק את החשבון ואת כל הסריקות השמורות בו?',
  deleteAccountBody: 'אי אפשר לבטל. הסריקות במכשיר הזה יישארו.',
  deleteFailed: 'המחיקה לא הצליחה. נסו שוב.',
  welcomeTitle: 'ברוכים הבאים',
  landTitle: 'בודקים אם הפרי טוב – עם הטלפון',
  landSub: 'מצלמים פרי או ירק, ותוך שניות יודעים אם כדאי לקנות אותו, אם הוא בשל ואיך לשמור עליו.',
  landRow1: 'מצלמים את הפרי או הירק',
  landRow2: 'מקבלים ציון מ-1 עד 10',
  landRow3: 'וטיפ: מה לבדוק ביד ואיך לשמור',
  landBadgesWeb: 'בחינם · בלי הרשמה · בלי להתקין',
  landBadgesApp: 'בחינם · בלי הרשמה',
  landCta: 'בואו נבדוק פרי 📸',
  landSignIn: 'התחברות עם Google – לשמירת הסריקות',
  welcomeBody: 'התחברו כדי לשמור את הסריקות שלכם בחשבון – ולראות אותן מכל מכשיר.',
  continueWithout: 'המשך בלי חשבון',
  signInPrivacy: 'נשמרים רק השם, האימייל והסריקות שלכם (תוצאה ותמונה מוקטנת). אפשר למחוק את החשבון בכל רגע.',
  skip: 'דלגו',
  next: 'הבא',
  letsStart: 'בואו נתחיל',
  onb1Kicker: 'שלב 01 · צילום',
  onb1Title: 'מכוונים את המצלמה אל הפרי או הירק.',
  onb1Body: 'תמונה אחת, תשובה תוך שניות. בלי הרשמה.',
  onb1Chip: '⚡ תוצאה תוך שניות',
  onb2Kicker: 'שלב 02 · ציון איכות',
  onb2Title: 'ציון, שלב והסבר.',
  onb2Body: 'בשילות, טריות ופגמים – מה שרואים בתמונה, בציון מ-1 עד 10.',
  onb2Chip: '🍎 1/10 · לא מומלץ',
  onb3Kicker: 'שלב 03 · הסריקות שלי',
  onb3Title: 'כל סריקה נשמרת.',
  onb3Body: 'חוזרים לתוצאות, קונים חכם יותר, זורקים פחות.',
  onb3Chip: '🔴 רימון · טרי · 10',
  howItWorks: 'איך זה עובד',
  step1a: 'מצלמים', step1b: 'פרי או ירק אחד, מקרוב ובאור טוב.',
  step2a: 'המודל שלנו', step2b: 'מזהה מה זה ובודק את המראה: צבע, כתמים, ריקבון.',
  step3a: 'מקבלים', step3b: 'ציון מ-1 עד 10, המלצה וטיפ אחסון.',
  ratedFor: 'דירוג איכות זמין עכשיו ל:',
  ratedNote: (n: number) => `לסוגים האלה – ציון מדויק שעבר מבחן דיוק על תמונות שהמודל לא ראה. שאר הסוגים (המודל מזהה ${n} סוגים) מקבלים "ציון כללי": טרי או לא טרי, פחות מדויק.`,
  photoLimitsTitle: 'מה תמונה לא יכולה לדעת',
  photoLimits: ['מה קורה בתוך הפרי (ריקבון פנימי, מכה טרייה).', 'מתיקות, ובשילות של פירות שצבעם לא משתנה (הדרים, אבטיח, אבוקדו ירוק).', 'אם המזון בטוח לאכילה – זו הערכה חזותית בלבד.'],
  privacyTitle: 'פרטיות',
  privacyPolicy: 'מדיניות הפרטיות המלאה ↗',
  privacyDevice: 'התמונה נשלחת לניתוח בשרת שלנו ולא נשמרת שם, אלא אם בחרתם במפורש לשתף אותה לאימון המודל. ההיסטוריה נשמרת רק במכשיר. בלי פרסומות, בלי שירות בינה מלאכותית חיצוני.',
  privacySignedIn: 'התמונה נשלחת לניתוח בשרת שלנו ולא נשמרת שם. הסריקות (תוצאה ותמונה מוקטנת) נשמרות בחשבון שלכם, ורק אתם רואים אותן. בלי פרסומות, בלי שירות בינה מלאכותית חיצוני.',
  replayIntro: 'הצגת ההדרכה שוב',
  sample: 'דוגמה',
  samplesTitle: 'נסו דוגמה',
  samplesBody: 'אין פרי בהישג יד? בחרו תמונה ותראו איך זה עובד.',
  sampleNames: { banana: 'בננות', apple_rotten: 'תפוח', pomegranate: 'רימון' } as Record<string, string>,
  backToCamera: 'חזרה למצלמה',
  gallery: 'גלריה',
  share: 'שיתוף',
  shareText: (name: string, score: string) => `סרקתי ${name}${score} עם Scan Fruit AI – הערכה חזותית בלבד.`,
  pickBody: 'לא בטוחים ב־100%. מה זה? בחרו, ונבדוק את המצב שלו:',
  generalScore: 'ציון כללי',
  stageUse: 'מה עושים איתו עכשיו',
  chosenByYou: 'בחרתם את הסוג',
  savedInAccount: 'נשמר בחשבון שלכם – זמין גם באתר ובכל מכשיר.',
  recommendation: 'המלצה',
  confidence: 'ביטחון בזיהוי',
  notAvailable: 'לא זמין עדיין לסוג זה',
  whatWeSaw: 'מה זיהינו?',
  why: 'מה גרם למודל לחשוב כך?',
  retake: 'צילום נוסף',
  wasItRight: 'האם הזיהוי נכון?',
  yes: 'כן',
  no: 'לא',
  thanks: 'תודה! המשוב עוזר לשפר את המודל.',
  credits: 'קרדיט לנתונים',
  photoCredits: 'רשימת הצלמים המלאה ↗',
  creditsIntro: 'המודל אומן על מאגרי תמונות ציבוריים באישור הרישיון שלהם:',
  modelVersion: 'גרסת מודל',
  donateAsk: 'רוצים לעזור ללמד את המודל פירות מישראל?',
  donateButton: 'שיתוף התמונה',
  donateConsent: 'התמונה תישמר ותשמש לאימון המודל על פירות וירקות בישראל. נשלחים רק התמונה (מוקטנת, בלי מיקום ובלי פרטי מכשיר) והזיהוי. אין שם, חשבון או מזהה – לכן אי אפשר לשייך אותה אליכם, וגם לא למחוק אותה בהמשך. לא לשתף תמונה שמופיעים בה אנשים או מסמכים.',
  donateConfirm: 'מסכים/ה, לשתף',
  donateCancel: 'ביטול',
  donateSending: 'שולח…',
  donateThanks: 'תודה! התמונה נשלחה.',
  donateFailed: 'השליחה לא הצליחה. אפשר לנסות שוב.',
  visualOnlyBanner: 'הערכה חזותית בלבד',
  surveyTitle: 'שאלה קצרה',
  surveyQ: {
    better_fruit: 'מאז שהתחלתם להשתמש באפליקציה, אתם בוחרים פירות וירקות טובים יותר?',
    less_waste: 'מאז שהתחלתם להשתמש באפליקציה, אתם זורקים פחות פירות וירקות?',
  } as Record<string, string>,
  surveyA: { a_lot: 'כן, הרבה', a_little: 'קצת', no_change: 'לא השתנה', not_sure: 'לא בטוח/ה' } as Record<string, string>,
  surveyLater: 'לא עכשיו',
  surveyNever: 'לא לשאול שוב',
  surveyThanks: 'תודה! זה עוזר לנו לשפר.',
  surveyPrivacy: 'אנונימי: נשלחת רק התשובה, בלי תמונה ובלי פרטים מזהים.',
};
