// 1:1 port of ml/inference/decision.py::decide. Any change there must be mirrored here;
// __tests__/decision.parity.test.ts compares both on fixtures generated by
// scripts/gen_decision_fixtures.py.
import type { Bundle, HeadResult, Probs, ScanResult, Thresholds } from './types';
import { argmax } from './math';

export const DISCLAIMER_HE = 'חשוב: זו הערכה חזותית בלבד ואינה מבטיחה שהמזון בטוח לאכילה.';
const RETAKE_HE: Record<string, string> = {
  too_dark: 'התמונה חשוכה מדי. נסה לצלם בתאורה טובה יותר.',
  too_bright: 'התמונה בהירה מדי. נסה להימנע מאור ישיר.',
  overexposed: 'יש בתמונה אזורים שרופים מאור. נסה לצלם בזווית אחרת.',
  blurry: 'התמונה מטושטשת. החזק את הטלפון יציב ונסה שוב.',
  multiple_objects: 'זוהו כמה פריטים. צלם פרי או ירק אחד בכל פעם.',
};
const UNSURE_HE = 'לא הצלחתי לזהות את הפרי בוודאות. נסה לצלם אותו מקרוב ובתאורה טובה יותר.';
const NOT_PRODUCE_HE = 'לא זיהיתי פרי או ירק שאני מכיר בתמונה.';
const REC_HE: Record<string, string> = {
  discard: 'לא מומלץ לאכול – נראים סימני קלקול',
  eat_soon: 'כדאי לאכול בהקדם',
  eat_now: 'כדאי לאכול עכשיו',
  wait: 'כדאי לחכות – עדיין לא בשל',
  wait_little: 'כמעט בשל – כדאי לחכות עוד מעט',
  overripe: 'בשל מאוד – לאכול היום או להשתמש לבישול/אפייה',
  inspect: 'לא ניתן להעריך בוודאות – מומלץ לבדוק ידנית',
};
export const DEFAULT_THRESHOLDS: Thresholds = {
  produce_min_prob: 0.7,
  produce_min_margin: 0.15,
  ood_min_energy: null,
  head_min_prob: 0.55,
  spoiled_alert_prob: 0.4,
};
const UNKNOWN = 'unknown';

function empty(status: ScanResult['status'], message: string | null, conf: number | null = null): ScanResult {
  return {
    status, message_he: message, produce: null, produce_he: null, emoji: null, produce_confidence: conf,
    ripeness: null, freshness: null, visual_spoilage: null, recommendation: null, recommendation_he: null,
    explanation_he: [], disclaimer_he: DISCLAIMER_HE,
  };
}

function headResult(bundle: Bundle, head: 'ripeness' | 'freshness' | 'visual_spoilage', probs: number[] | undefined,
                    available: boolean, minProb: number): HeadResult {
  if (!available || !probs) return { label: null, label_he: null, confidence: null, available: false };
  const i = argmax(probs);
  const conf = probs[i];
  if (conf < minProb) return { label: UNKNOWN, label_he: bundle.label_he[head][UNKNOWN], confidence: conf, available: true };
  const lbl = bundle.outputs[head][i];
  return { label: lbl, label_he: bundle.label_he[head][lbl], confidence: conf, available: true };
}

export function decide(bundle: Bundle, probs: Probs, qualityReason: string | null = null,
                       energyScore: number | null = null, thresholds?: Partial<Thresholds>): ScanResult {
  const t: Thresholds = { ...DEFAULT_THRESHOLDS, ...bundle.thresholds, ...(thresholds ?? {}) };
  if (qualityReason) return empty('retake', RETAKE_HE[qualityReason] ?? UNSURE_HE);

  const p = probs.produce!;
  const order = p.map((v, i) => [v, i] as const).sort((a, b) => b[0] - a[0] || a[1] - b[1]).map(([, i]) => i);
  const top = order[0];
  const conf = p[top];
  const margin = conf - (order.length > 1 ? p[order[1]] : 0);
  if (t.ood_min_energy !== null && energyScore !== null && energyScore < t.ood_min_energy) {
    return empty('unsure', UNSURE_HE, conf);
  }
  const name = bundle.outputs.produce[top];
  const meta = bundle.produce_meta[name];
  if (meta.is_negative_class) return empty('not_produce', NOT_PRODUCE_HE, conf);
  if (conf < t.produce_min_prob || margin < t.produce_min_margin) return empty('unsure', UNSURE_HE, conf);

  const sup = new Set(bundle.supported_heads[name] ?? []);
  const r = headResult(bundle, 'ripeness', probs.ripeness, sup.has('ripeness'), t.head_min_prob);
  const f = headResult(bundle, 'freshness', probs.freshness, sup.has('freshness'), t.head_min_prob);
  const s = headResult(bundle, 'visual_spoilage', probs.visual_spoilage, sup.has('visual_spoilage'), t.head_min_prob);
  const res: ScanResult = {
    ...empty('ok', null, conf), produce: name, produce_he: meta.he, emoji: meta.emoji,
    ripeness: r, freshness: f, visual_spoilage: s,
  };

  let pSpoiled = 0;
  if (f.available && probs.freshness) pSpoiled = probs.freshness[bundle.outputs.freshness.indexOf('spoiled')];
  if (s.available && probs.visual_spoilage) {
    pSpoiled = Math.max(pSpoiled, probs.visual_spoilage[bundle.outputs.visual_spoilage.indexOf('severe')]);
  }
  let rec: string;
  if (pSpoiled >= t.spoiled_alert_prob) {
    rec = 'discard';
    res.explanation_he.push('זוהו סימנים חזותיים שמתאימים בדרך כלל לקלקול או ריקבון.');
  } else if (r.available && r.label !== null && r.label !== UNKNOWN) {
    rec = ({ unripe: 'wait', partially_ripe: 'wait_little', ripe: 'eat_now', overripe: 'overripe' } as Record<string, string>)[r.label];
    res.explanation_he.push(`הצבע והמראה החיצוני תואמים בדרך כלל ל${meta.he} במצב '${r.label_he}'.`);
  } else if (f.available && f.label === 'fresh') {
    rec = 'eat_now';
    res.explanation_he.push('המראה החיצוני תואם בדרך כלל לפרי טרי. לא זוהו סימני ריקבון משמעותיים.');
  } else if (f.available && f.label === 'declining') {
    rec = 'eat_soon';
    res.explanation_he.push('נראים סימנים ראשונים לירידה בטריות.');
  } else {
    rec = 'inspect';
    res.explanation_he.push('למודל אין מספיק ביטחון או נתוני אימון כדי להעריך בשילות/טריות לסוג זה.');
  }
  res.recommendation = rec;
  res.recommendation_he = REC_HE[rec];
  return res;
}
