// 1:1 port of ml/inference/decision.py::decide. Any change there must be mirrored here;
// __tests__/decision.parity.test.ts compares both on fixtures generated by
// scripts/gen_decision_fixtures.py.
import type { Bundle, HeadResult, Probs, ScanResult, Thresholds } from './types';
import { argmax } from './math';

export const DISCLAIMER_HE = 'חשוב: זו הערכה חזותית בלבד ואינה מבטיחה שהמזון בטוח לאכילה.';
const RETAKE_HE: Record<string, string> = {
  too_dark: 'התמונה חשוכה מדי. נסה לצלם בתאורה טובה יותר.',
  too_bright: 'התמונה בהירה מדי. נסה להימנע מאור ישיר.',
  overexposed: 'יש בתמונה אזורים שרופים מאור. נסה לצלם בזווית אחרת.',
  blurry: 'התמונה מטושטשת. החזק את הטלפון יציב ונסה שוב.',
  multiple_objects: 'זוהו כמה פריטים. צלם פרי או ירק אחד בכל פעם.',
};
const UNSURE_HE = 'לא הצלחתי לזהות את הפרי בוודאות. נסה לצלם אותו מקרוב ובתאורה טובה יותר.';
// Israeli Ministry of Health: discard mouldy food whole (docs/research/food-quality.md). Mirrors decision.py.
const MOULD_RULE_HE = 'לפי משרד הבריאות: מזון שצמח עליו עובש – לזרוק בשלמותו, ולא לחתוך רק את החלק שנראה עבש.';
const NOT_PRODUCE_HE = 'לא זיהיתי פרי או ירק שאני מכיר בתמונה.';
const REC_HE: Record<string, string> = {
  discard: 'לא מומלץ לאכול – נראים סימני קלקול',
  eat_soon: 'כדאי לאכול בהקדם',
  eat_now: 'כדאי לאכול עכשיו',
  wait: 'כדאי לחכות – עדיין לא בשל',
  wait_little: 'כמעט בשל – כדאי לחכות עוד מעט',
  overripe: 'בשל מאוד – לאכול היום או להשתמש לבישול/אפייה',
  check_defects: 'נראים פגמים או סימני קלקול – בדקו את הפרי לפני שאוכלים',
  inspect: 'לא ניתן להעריך בוודאות – מומלץ לבדוק ידנית',
};
export const DEFAULT_THRESHOLDS: Thresholds = {
  produce_min_prob: 0.7,
  produce_min_margin: 0.15,
  ood_min_energy: null,
  head_min_prob: 0.55,
  spoiled_alert_prob: 0.4,
};
const UNKNOWN = 'unknown';

function empty(status: ScanResult['status'], message: string | null, conf: number | null = null): ScanResult {
  return {
    status, message_he: message, produce: null, produce_he: null, emoji: null, produce_confidence: conf,
    ripeness: null, freshness: null, visual_spoilage: null, recommendation: null, recommendation_he: null,
    explanation_he: [], score: null, score_reason_he: null, disclaimer_he: DISCLAIMER_HE, general_score: false,
    condition: null, overall: null, condition_score: null, ripeness_score: null, condition_confidence: null,
    low_confidence: false, issues_he: [],
  };
}

// Condition head v2 — mirrors decision.py _decide_condition (docs/quality-scoring.md §4-5).
const CONDITION_LABEL_HE: Record<string, string> = {
  good: 'תקין – בלי פגמים או סימני קלקול נראים', bad: 'נראים פגמים או סימני קלקול',
  early: 'סימנים ראשונים של ירידה באיכות', rotten: 'נראים סימני ריקבון',
};
const GRADE_POINTS = { good: 100, early: 60, rotten: 10 };
const LOW_CONF_CAP = 60;
const LOW_CONF_CONDITION_HE = 'המצב לא ברור מספיק מהתמונה, לכן הציון שמרני. צלמו מקרוב, באור טוב ומכמה צדדים.';
const ISSUE_HE: Record<string, string> = {
  bad: 'נראים פגמים או סימני קלקול', early: 'סימנים ראשונים: כתמים, ריכוך או פגמים קטנים',
  rotten: 'נראים סימני ריקבון', overripe: 'בשל מאוד', unripe: 'עדיין לא בשל',
  partially_ripe: 'עוד לא בשל לגמרי', unclear: 'המצב לא ברור מהתמונה',
};
const halfUp = (x: number) => Math.floor(x + 0.5); // = decision.py _half_up
const round4 = (x: number) => Math.round(x * 1e4) / 1e4;

// Coarse heads (good vs bad only) — mirrors decision.py COARSE; marked "<head>~coarse" in supported_heads.
const COARSE: Record<'freshness' | 'visual_spoilage', [string, string[], string]> = {
  freshness: ['fresh', ['declining', 'spoiled'], 'not_fresh'],
  visual_spoilage: ['none', ['mild', 'severe'], 'defects'],
};
const COARSE_LABEL_HE: Record<string, string> = { not_fresh: 'לא טרי', defects: 'פגמים נראים' };
const COARSE_BAD_POINTS = 3;

function coarseHead(bundle: Bundle, head: 'freshness' | 'visual_spoilage', probs: number[] | undefined,
                    minProb: number): HeadResult {
  if (!probs) return { label: null, label_he: null, confidence: null, available: false };
  const [good, , group] = COARSE[head];
  const pGood = probs[bundle.outputs[head].indexOf(good)];
  const pBad = 1 - pGood;
  if (pGood >= minProb) return { label: good, label_he: bundle.label_he[head][good], confidence: pGood, available: true };
  if (pBad >= minProb) return { label: group, label_he: COARSE_LABEL_HE[group], confidence: pBad, available: true };
  return { label: UNKNOWN, label_he: bundle.label_he[head][UNKNOWN], confidence: Math.max(pGood, pBad), available: true };
}

// 1-10 visual quality score — mirrors decision.py quality_score (docs/research/quality-score.md).
const SCORE_POINTS: Record<'freshness' | 'visual_spoilage' | 'ripeness', Record<string, number>> = {
  freshness: { fresh: 10, declining: 6, spoiled: 1 },
  visual_spoilage: { none: 10, mild: 5, severe: 1 },
  ripeness: { unripe: 5, partially_ripe: 8, ripe: 10, overripe: 6 },
};
const SCORE_REASON_HE: Record<string, string> = {
  good: 'נראה טרי, בלי סימני קלקול נראים.',
  ripe: 'בשל – טוב לאכילה עכשיו.',
  spoilage: 'נראים סימני ריקבון, עובש או פגמים בקליפה.',
  spoiled: 'המראה מתאים לפרי שהתקלקל.',
  declining: 'מתחיל לאבד טריות – כדאי לאכול בקרוב.',
  not_fresh: 'המראה מראה ירידה בטריות או קלקול.',
  unripe: 'עדיין לא בשל – יהיה טעים יותר בעוד כמה ימים.',
  overripe: 'בשל מאוד – לאכול היום או להשתמש לאפייה.',
};
const GENERAL_SCORE_HE = 'ציון כללי: לסוג הזה עוד אין בדיקת דיוק משלו, לכן ההערכה (טרי / לא טרי) פחות מדויקת.';
const LOW_CONF_SCORE_HE = 'לא ניתן לדרג בביטחון מהתמונה הזו – נסו לצלם מקרוב ובאור טוב.';
const NO_SCORE_HE = 'עדיין אין דירוג איכות לסוג הזה – המודל מזהה אותו אבל עוד לא אומן להעריך את מצבו.';

export function qualityScore(bundle: Bundle, probs: Probs, available: Record<'freshness' | 'visual_spoilage' | 'ripeness', boolean>,
                             discard: boolean, coarse: Set<string> = new Set()): [number | null, string] {
  const comps: [('freshness' | 'visual_spoilage' | 'ripeness'), number][] = [];
  for (const head of ['freshness', 'visual_spoilage', 'ripeness'] as const) {
    const p = probs[head];
    if (available[head] && p) {
      let e = 0;
      if (coarse.has(head)) {
        const pg = p[bundle.outputs[head].indexOf(COARSE[head as 'freshness' | 'visual_spoilage'][0])];
        e = pg * 10 + (1 - pg) * COARSE_BAD_POINTS;
      } else {
        bundle.outputs[head].forEach((lbl, i) => { e += p[i] * SCORE_POINTS[head][lbl]; });
      }
      comps.push([head, e]);
    }
  }
  if (comps.length === 0) return [null, NO_SCORE_HE];
  let [worst, val] = comps[0];
  for (const [h, v] of comps.slice(1)) if (v < val) { worst = h; val = v; }
  let score = Math.min(10, Math.max(1, Math.floor(val + 0.5)));
  if (discard) score = Math.min(score, 2);
  const p = probs[worst]!;
  let top = 0;
  p.forEach((v, i) => { if (v > p[top]) top = i; });
  const topLabel = bundle.outputs[worst][top];
  let reason: string;
  if (score >= 8) reason = worst === 'ripeness' ? 'ripe' : 'good';
  else if (worst === 'visual_spoilage') reason = 'spoilage';
  else if (worst === 'freshness' && coarse.has(worst)) reason = 'not_fresh';
  else if (worst === 'freshness') reason = topLabel === 'spoiled' ? 'spoiled' : 'declining';
  else reason = topLabel === 'overripe' ? 'overripe' : 'unripe';
  return [score, SCORE_REASON_HE[reason]];
}

function headResult(bundle: Bundle, head: 'ripeness' | 'freshness' | 'visual_spoilage', probs: number[] | undefined,
                    available: boolean, minProb: number): HeadResult {
  if (!available || !probs) return { label: null, label_he: null, confidence: null, available: false };
  const i = argmax(probs);
  const conf = probs[i];
  if (conf < minProb) return { label: UNKNOWN, label_he: bundle.label_he[head][UNKNOWN], confidence: conf, available: true };
  const lbl = bundle.outputs[head][i];
  return { label: lbl, label_he: bundle.label_he[head][lbl], confidence: conf, available: true };
}

export function decide(bundle: Bundle, probs: Probs, qualityReason: string | null = null,
                       energyScore: number | null = null, thresholds?: Partial<Thresholds>,
                       chosenProduce?: string): ScanResult {
  const t: Thresholds = { ...DEFAULT_THRESHOLDS, ...bundle.thresholds, ...(thresholds ?? {}) };
  if (chosenProduce) return assess(bundle, probs, t, chosenProduce, probs.produce![bundle.outputs.produce.indexOf(chosenProduce)] ?? null, true);
  if (qualityReason) return empty('retake', RETAKE_HE[qualityReason] ?? UNSURE_HE);

  const p = probs.produce!;
  const order = p.map((v, i) => [v, i] as const).sort((a, b) => b[0] - a[0] || a[1] - b[1]).map(([, i]) => i);
  const top = order[0];
  const conf = p[top];
  const margin = conf - (order.length > 1 ? p[order[1]] : 0);
  if (t.ood_min_energy !== null && energyScore !== null && energyScore < t.ood_min_energy) {
    return empty('unsure', UNSURE_HE, conf);
  }
  const name = bundle.outputs.produce[top];
  const meta = bundle.produce_meta[name];
  if (meta.is_negative_class) return empty('not_produce', NOT_PRODUCE_HE, conf);
  if (conf < t.produce_min_prob || margin < t.produce_min_margin) return empty('unsure', UNSURE_HE, conf);
  return assess(bundle, probs, t, name, conf, false);
}

/** Quality assessment once the produce type is known (by the model, or picked by the user after "unsure"). */
function assess(bundle: Bundle, probs: Probs, t: Thresholds, name: string, conf: number | null, byUser: boolean): ScanResult {
  const meta = bundle.produce_meta[name];
  const sup = new Set(bundle.supported_heads[name] ?? []);
  if ((sup.has('condition') || sup.has('condition~graded')) && Array.isArray(probs.condition)) return assessCondition(bundle, probs, t, name, conf, byUser);
  const coarse = new Set<string>((['freshness', 'visual_spoilage'] as const).filter((h) => !sup.has(h) && sup.has(`${h}~coarse`)));
  // "freshness~general" (mirrors decision.py): no verified head for this type; the general fresh-vs-spoiled model
  // gives a coarse good/bad freshness from probs.freshness_general[produce] = P(spoiled).
  const general = sup.has('freshness~general') && Array.isArray(probs.freshness_general) && !sup.has('freshness') && !coarse.has('freshness');
  if (general) {
    const pb = probs.freshness_general![bundle.outputs.produce.indexOf(name)];
    probs = { ...probs, freshness: bundle.outputs.freshness.map((l) => (l === 'fresh' ? 1 - pb : l === 'spoiled' ? pb : 0)) };
    sup.add('freshness~coarse');
    coarse.add('freshness');
  }
  const r = headResult(bundle, 'ripeness', probs.ripeness, sup.has('ripeness'), t.head_min_prob);
  const f = coarse.has('freshness') ? coarseHead(bundle, 'freshness', probs.freshness, t.head_min_prob)
    : headResult(bundle, 'freshness', probs.freshness, sup.has('freshness'), t.head_min_prob);
  const s = coarse.has('visual_spoilage') ? coarseHead(bundle, 'visual_spoilage', probs.visual_spoilage, t.head_min_prob)
    : headResult(bundle, 'visual_spoilage', probs.visual_spoilage, sup.has('visual_spoilage'), t.head_min_prob);
  const res: ScanResult = {
    ...empty('ok', null, conf), produce: name, produce_he: meta.he, emoji: meta.emoji,
    ripeness: r, freshness: f, visual_spoilage: s, ...(byUser ? { chosen_by_user: true } : {}),
  };

  let pSpoiled = 0;
  if (f.available && !coarse.has('freshness') && probs.freshness) pSpoiled = probs.freshness[bundle.outputs.freshness.indexOf('spoiled')];
  if (s.available && !coarse.has('visual_spoilage') && probs.visual_spoilage) {
    pSpoiled = Math.max(pSpoiled, probs.visual_spoilage[bundle.outputs.visual_spoilage.indexOf('severe')]);
  }
  let rec: string;
  if (pSpoiled >= t.spoiled_alert_prob) {
    rec = 'discard';
    res.explanation_he.push('זוהו סימנים חזותיים שמתאימים בדרך כלל לקלקול או ריקבון.');
    res.explanation_he.push(MOULD_RULE_HE);
  } else if ((f.available && f.label === 'not_fresh') || (s.available && s.label === 'defects')) {
    rec = 'check_defects';
    res.explanation_he.push('המראה מתאים לפרי עם פגמים, מכות או סימני ריקבון.');
    res.explanation_he.push(MOULD_RULE_HE);
  } else if (r.available && r.label !== null && r.label !== UNKNOWN) {
    rec = ({ unripe: 'wait', partially_ripe: 'wait_little', ripe: 'eat_now', overripe: 'overripe' } as Record<string, string>)[r.label];
    res.explanation_he.push(`הצבע והמראה החיצוני תואמים בדרך כלל ל${meta.he} במצב '${r.label_he}'.`);
    if (meta.ripeness_note_he) res.explanation_he.push(meta.ripeness_note_he);
  } else if (f.available && f.label === 'fresh') {
    rec = 'eat_now';
    res.explanation_he.push('המראה החיצוני תואם בדרך כלל לפרי טרי. לא זוהו סימני ריקבון משמעותיים.');
  } else if (f.available && f.label === 'declining') {
    rec = 'eat_soon';
    res.explanation_he.push('נראים סימנים ראשונים לירידה בטריות.');
  } else if (s.available && s.label === 'none') {
    rec = 'eat_now';
    res.explanation_he.push('לא נראים פגמים או סימני ריקבון בקליפה.');
  } else {
    rec = 'inspect';
    res.explanation_he.push('למודל אין מספיק ביטחון או נתוני אימון כדי להעריך בשילות/טריות לסוג זה.');
  }
  res.recommendation = rec;
  res.recommendation_he = REC_HE[rec];
  [res.score, res.score_reason_he] = qualityScore(
    bundle, probs, { freshness: f.available, visual_spoilage: s.available, ripeness: r.available }, rec === 'discard', coarse);
  if (rec === 'inspect' && res.score !== null) [res.score, res.score_reason_he] = [null, LOW_CONF_SCORE_HE];
  if (general && res.score !== null) {
    res.general_score = true;
    res.explanation_he.push(GENERAL_SCORE_HE);
  }
  return res;
}

function assessCondition(bundle: Bundle, probs: Probs, t: Thresholds, name: string, conf: number | null, byUser: boolean): ScanResult {
  const meta = bundle.produce_meta[name];
  const sup = new Set(bundle.supported_heads[name] ?? []);
  const idx = bundle.outputs.produce.indexOf(name);
  const pg = probs.condition![idx];
  const graded = sup.has('condition~graded') && Array.isArray(probs.condition_rot);
  const pr = graded ? probs.condition_rot![idx] : 0; // P(rotten | not good)
  const cconf = Math.max(pg, 1 - pg);
  const low = cconf < (t.condition_abstain?.[name] ?? 0.5);
  const good = pg >= 0.5;
  const label = good ? 'good' : !graded ? 'bad' : pr >= 0.5 ? 'rotten' : 'early';
  const cond: HeadResult = { label, label_he: CONDITION_LABEL_HE[label], confidence: round4(cconf), available: true };
  const r = headResult(bundle, 'ripeness', probs.ripeness, sup.has('ripeness'), t.head_min_prob);
  const none: HeadResult = { label: null, label_he: null, confidence: null, available: false };
  const res: ScanResult = {
    ...empty('ok', null, conf), produce: name, produce_he: meta.he, emoji: meta.emoji,
    ripeness: r, freshness: none, visual_spoilage: none, condition: cond, ...(byUser ? { chosen_by_user: true } : {}),
  };
  // Reliability ceiling measured on unseen photo sources (decision.py): the score never claims more.
  if (graded) {
    const pc = Math.min(pg, t.condition_max_p_type?.[name] ?? t.condition_max_p_graded ?? 1); // = decision.py
    res.condition_score = halfUp(GRADE_POINTS.good * pc + GRADE_POINTS.early * (1 - pc) * (1 - pr) + GRADE_POINTS.rotten * (1 - pc) * pr);
  } else res.condition_score = halfUp(100 * Math.min(pg, t.condition_max_p ?? 1));
  res.condition_confidence = round4(cconf);
  let overall = res.condition_score;
  if (r.available && probs.ripeness) {
    let e = 0;
    bundle.outputs.ripeness.forEach((lbl, i) => { e += probs.ripeness![i] * SCORE_POINTS.ripeness[lbl]; });
    res.ripeness_score = halfUp(10 * e);
    overall = Math.min(overall, res.ripeness_score);
  }
  if (low) {
    res.low_confidence = true;
    overall = Math.min(overall, LOW_CONF_CAP);
  }
  res.overall = overall;
  res.score = Math.min(10, Math.max(1, halfUp(overall / 10)));

  const rip = r.available && r.label !== null && r.label !== UNKNOWN ? r.label : null;
  let rec: string;
  if (low) {
    rec = 'inspect';
    res.explanation_he.push(LOW_CONF_CONDITION_HE);
    res.issues_he!.push(ISSUE_HE.unclear);
  } else if (label === 'early') {
    rec = 'eat_soon';
    res.explanation_he.push('נראים סימנים ראשונים של ירידה באיכות (כתמים, ריכוך או פגמים קטנים), בלי סימני ריקבון.');
    res.issues_he!.push(ISSUE_HE.early);
  } else if (!good) {
    rec = 'check_defects';
    res.explanation_he.push('המראה מתאים לפרי עם פגמים, מכות או סימני ריקבון.');
    res.explanation_he.push(MOULD_RULE_HE);
    res.issues_he!.push(ISSUE_HE[label === 'rotten' ? 'rotten' : 'bad']);
  } else if (rip) {
    rec = ({ unripe: 'wait', partially_ripe: 'wait_little', ripe: 'eat_now', overripe: 'overripe' } as Record<string, string>)[rip];
    res.explanation_he.push(`הצבע והמראה החיצוני תואמים בדרך כלל ל${meta.he} במצב '${r.label_he}'.`);
    if (meta.ripeness_note_he) res.explanation_he.push(meta.ripeness_note_he);
  } else {
    rec = 'eat_now';
    res.explanation_he.push('לא נראים פגמים או סימני קלקול.');
  }
  if (rip === 'overripe' || rip === 'unripe' || rip === 'partially_ripe') res.issues_he!.push(ISSUE_HE[rip]);
  res.recommendation = rec;
  res.recommendation_he = REC_HE[rec];
  if (low) res.score_reason_he = LOW_CONF_CONDITION_HE;
  else if (label === 'early') res.score_reason_he = SCORE_REASON_HE.declining;
  else if (!good) res.score_reason_he = SCORE_REASON_HE.spoilage;
  else if (res.ripeness_score !== null && res.ripeness_score! < res.condition_score && overall < 80) {
    res.score_reason_he = SCORE_REASON_HE[rip === 'overripe' ? 'overripe' : 'unripe'];
  } else res.score_reason_he = SCORE_REASON_HE[rip === 'ripe' ? 'ripe' : 'good'];
  return res;
}
