import { ScrollView, StyleSheet, Text } from 'react-native';

import creditsJson from '../../assets/model/credits.json';
import { he } from '../ui/strings';

// Generated by scripts/gen_credits.py from the shipped bundle's training datasets + the registry.
interface Credit { dataset_id: string; name: string; license: string; url: string; attribution: string }
const credits = creditsJson as unknown as { model_id: string; datasets: Credit[] };
export default function CreditsScreen() {
  return (
    <ScrollView contentContainerStyle={styles.pad}>
      <Text style={styles.body}>{he.creditsIntro}</Text>
      {credits.datasets.map((d) => (
        <Text key={d.dataset_id} style={styles.item}>
          • {d.name} — {d.license}{d.attribution ? `\n  ${d.attribution}` : ''}
        </Text>
      ))}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  pad: { padding: 16, gap: 12 },
  body: { fontSize: 16, textAlign: 'left' },
  item: { fontSize: 14, color: '#333', textAlign: 'left' },
});
